### ISSUE TITLE
Getting Invalid signature

### ISSUE THREAD

**Issue by liamseys** [david-vde/cex.io-php#1]
When performing a call to fetch Balances of an account I receive "Invalid signature".

**Comment by david-vde** [comment]
Hello 

Thank you for your message,

it should works but keep in mind that this is under development.

can you put your code (without credentials obviously?) thank you

**Comment by david-vde** [comment]
Can you go to this file : 

./src/Client.php

at line 288

`
$nonce = (int)(microtime(true) * 10000);
`

and please print the value of the $nonce variable.

Maybe if you dont have a 64bit OS it value is wrong I havent tested with

THanks

**Comment by david-vde** [comment]
Also can you try to generat a new API key? It is certainly related to the nonce.

Its really annoying to manage

**Comment by david-vde** [comment]
Ok I investigated this by myself and I fixed the issue.

Update the client to 0.3.1 version.

If you still have problem to sign the request, just generate another API key on CEX.io it should solve your problem.
